name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make deps
    - name: Static Type Check - Mypy
      run: make static_type_check
    - name: Code Check - Pylint
      run: make pylint
    - name: Run test
      run: |
        make -e test
        codecov